import React, { useCallback, useEffect, useState, useRef } from 'react';
import { useParams } from 'react-router-dom';
import LeftSideBar from './LeftSideBar';
import RightSideBar from './RightSideBar';
import WorkspaceCanvas, { type WorkspaceMode } from './WorkspaceCanvas';
import { WorkspaceProvider, useWorkspace } from './WorkSpace';
import type { WorkspaceTable } from './WorkSpace';
import ImportModal from './components/ImportModal';
import ExportModal from './components/ExportModal';
import ImportResultModal from './components/ImportResultModal';
import ImportRetryModal from './components/ImportRetryModal';
import type { ExportDatabase } from './components/ExportModal';
import BuildSuccessIcon from '../../assets/icons/build_success_icon.svg?react';
import { ErdWebSocketClient } from '../../services/websocket';
import { WebSocketTestPanel } from '../../components/common/WebSocketTestPanel';
import { useAuthStore } from '../../stores/authStore';
import RemoteCursor from './components/RemoteCursor';
import type { RemoteCursor as RemoteCursorType } from '../../services/websocket/types';

const dummySqlPreview: Record<ExportDatabase, string> = {
  mysql: `-- MySQL Export 예시
CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO customers (name, email)
VALUES
  ('홍길동', 'hong.gildong@example.com'),
  ('김영희', 'kim.younghee@example.com');`,
  postgresql: `-- PostgreSQL Export 예시
CREATE TABLE customers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO customers (name, email)
VALUES
  ('홍길동', 'hong.gildong@example.com'),
  ('김영희', 'kim.younghee@example.com');`,
};

const IMPORT_ERROR_SQL = `CREATE TABLE "snapshots" (
  "snapshot_key" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_key" INTEGER NOT NULL,
  "created_by" INTEGER NOT NULL,
  "name" VARCHAR(500) NOT NULL DEFAULT '',
  "schema" JSONB NOT NULL DEFAULT '{}',
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);`;

const IMPORT_ERROR_CHANGE_SUMMARY = [
  'snapshots.snapshot_key 컬럼을 BIGINT IDENTITY로 수정했습니다.',
  'schema 컬럼을 JSONB 타입으로 지정하여 JSON 구조 저장을 지원합니다.',
  'created_at 컬럼에 기본값 now()를 추가하여 생성 시간을 자동 저장합니다.',
];

const IMPORT_CORRECTED_TABLES: WorkspaceTable[] = [
  {
    id: 'table-projects',
    name: 'projects',
    identifier: 'projects',
    x: 180,
    y: 140,
    color: 'blue',
    columns: [
      {
        id: 'column-projects-project-key',
        isKey: true,
        logicalName: '프로젝트 키',
        physicalName: 'project_key',
        domain: 'PK',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 식별자',
      },
      {
        id: 'column-projects-name',
        isKey: false,
        logicalName: '프로젝트명',
        physicalName: 'name',
        domain: 'VARCHAR',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 이름',
      },
      {
        id: 'column-projects-owner',
        isKey: false,
        logicalName: '생성자',
        physicalName: 'created_by',
        domain: 'INTEGER',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '프로젝트 생성자',
      },
    ],
  },
  {
    id: 'table-snapshots',
    name: 'snapshots',
    identifier: 'snapshots',
    x: 420,
    y: 120,
    color: 'user2',
    columns: [
      {
        id: 'column-snapshots-key',
        isKey: true,
        logicalName: '스냅샷 키',
        physicalName: 'snapshot_key',
        domain: 'PK',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '스냅샷 식별자',
      },
      {
        id: 'column-snapshots-project-key',
        isKey: false,
        logicalName: '프로젝트 키',
        physicalName: 'project_key',
        domain: 'INTEGER',
        dataType: 'INTEGER',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 프로젝트',
      },
      {
        id: 'column-snapshots-schema',
        isKey: false,
        logicalName: '스키마',
        physicalName: 'schema',
        domain: 'JSONB',
        dataType: 'JSONB',
        allowNull: 'NOT NULL',
        defaultValue: '{}',
        comment: 'ERD JSON 데이터',
      },
      {
        id: 'column-snapshots-created-at',
        isKey: false,
        logicalName: '생성 일시',
        physicalName: 'created_at',
        domain: 'TIMESTAMPTZ',
        dataType: 'TIMESTAMPTZ',
        allowNull: 'NOT NULL',
        defaultValue: 'now()',
        comment: '생성 시각',
      },
    ],
  },
  {
    id: 'table-entities',
    name: 'entities',
    identifier: 'entities',
    x: 260,
    y: 340,
    color: 'user3',
    columns: [
      {
        id: 'column-entities-key',
        isKey: true,
        logicalName: '엔티티 키',
        physicalName: 'entity_key',
        domain: 'PK',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '엔티티 식별자',
      },
      {
        id: 'column-entities-snapshot-key',
        isKey: false,
        logicalName: '스냅샷 키',
        physicalName: 'snapshot_key',
        domain: 'BIGINT',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 스냅샷',
      },
      {
        id: 'column-entities-name',
        isKey: false,
        logicalName: '엔티티명',
        physicalName: 'name',
        domain: 'VARCHAR',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: 'ERD 엔티티 이름',
      },
    ],
  },
  {
    id: 'table-entity-columns',
    name: 'entity_columns',
    identifier: 'entity_columns',
    x: 520,
    y: 320,
    color: 'user4',
    columns: [
      {
        id: 'column-entity-columns-key',
        isKey: true,
        logicalName: '컬럼 키',
        physicalName: 'entity_column_key',
        domain: 'PK',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: 'IDENTITY',
        comment: '엔티티 컬럼 식별자',
      },
      {
        id: 'column-entity-columns-entity-key',
        isKey: false,
        logicalName: '엔티티 키',
        physicalName: 'entity_key',
        domain: 'BIGINT',
        dataType: 'BIGINT',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '연결된 엔티티',
      },
      {
        id: 'column-entity-columns-name',
        isKey: false,
        logicalName: '컬럼명',
        physicalName: 'column_name',
        domain: 'VARCHAR',
        dataType: 'VARCHAR(255)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '필드 명칭',
      },
      {
        id: 'column-entity-columns-type',
        isKey: false,
        logicalName: '데이터 타입',
        physicalName: 'data_type',
        domain: 'VARCHAR',
        dataType: 'VARCHAR(100)',
        allowNull: 'NOT NULL',
        defaultValue: '',
        comment: '데이터 타입',
      },
    ],
  },
];

type ImportResultState = {
  type: 'error';
  correctedSql: string;
  changeSummary: string[];
  tables: WorkspaceTable[];
};

const cloneTables = (tables: WorkspaceTable[]): WorkspaceTable[] =>
  tables.map((table) => ({
    ...table,
    columns: table.columns.map((column) => ({ ...column })),
  }));

interface WorkspaceLayoutProps {
  mode?: WorkspaceMode;
}

const WorkspaceLayout: React.FC<WorkspaceLayoutProps> = ({ mode = 'edit' }) => {
  const { activeTool, setActiveTool, replaceTables, updateTablePosition } = useWorkspace();
  const isViewMode = mode === 'view';
  const [sqlPreview, setSqlPreview] = useState('');
  const [isPreviewLoading, setIsPreviewLoading] = useState(false);
  const [isCopying, setIsCopying] = useState(false);
  const [showCopyToast, setShowCopyToast] = useState(false);
  const [isImportProcessing, setIsImportProcessing] = useState(false);
  const [importResult, setImportResult] = useState<ImportResultState | null>(
    null,
  );
  const [isImportResultOpen, setIsImportResultOpen] = useState(false);
  const [isImportRetryOpen, setIsImportRetryOpen] = useState(false);

  // URL에서 projectKey 가져오기
  const params = useParams<{ projectKey: string }>();
  const setProjectKey = useAuthStore((state) => state.setProjectKey);

  // WebSocket 관련 상태
  const wsClientRef = useRef<ErdWebSocketClient | null>(null);
  const [isWsConnected, setIsWsConnected] = useState(false);
  const currentUser = useAuthStore((state) => state.currentUser);

  // 원격 커서 상태 (다른 사용자들의 커서)
  const [remoteCursors, setRemoteCursors] = useState<Record<string, RemoteCursorType>>({});

  // projectKey를 authStore에 저장
  useEffect(() => {
    if (params.projectKey) {
      const projectKeyNum = parseInt(params.projectKey, 10);
      if (!isNaN(projectKeyNum)) {
        setProjectKey(projectKeyNum);
      }
    }
  }, [params.projectKey, setProjectKey]);

  // WebSocket 초기화
  useEffect(() => {
    if (isViewMode) return; // 뷰어 모드에서는 WebSocket 사용 안 함

    // authStore에서 실제 값 가져오기
    const projectKey = useAuthStore.getState().projectKey;

    // projectKey가 없으면 연결하지 않음
    if (!projectKey) {
      console.warn('⚠️ No projectKey found, skipping WebSocket connection');
      return;
    }

    console.log('🔌 Initializing WebSocket...');
    console.log('Project Key:', projectKey);
    console.log('User:', currentUser);

    // accessToken은 임시로 빈 문자열 (쿠키로 인증 처리)
    const wsClient = new ErdWebSocketClient({
      projectKey,
      accessToken: '',
    });

    // 이벤트 핸들러 등록
    wsClient.setEventHandlers({
      onTableMove: (event) => {
        console.log('📥 Received TABLE_MOVE:', event);
        const tableEvent = event.event as { tableKey: number; xPosition: number; yPosition: number };

        // 자기 이벤트는 무시 (이미 로컬 업데이트 완료)
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 다른 사용자의 테이블 이동 → 화면 업데이트
        updateTablePosition(`table-${tableEvent.tableKey}`, {
          x: tableEvent.xPosition,
          y: tableEvent.yPosition,
        });
      },
      onCursorMove: (event) => {
        console.log('📥 Received CURSOR_MOVE:', event);
        const cursorEvent = event.event as {
          userEmail?: string;
          userName?: string;
          userColor?: string;
          xPosition: number;
          yPosition: number;
        };

        // 자기 커서는 무시
        if (event.userKey === currentUser?.userKey) {
          return;
        }

        // 다른 사용자의 커서 업데이트
        const userEmail = cursorEvent.userEmail || `user-${event.userKey}`;
        setRemoteCursors((prev) => ({
          ...prev,
          [userEmail]: {
            userEmail,
            userName: cursorEvent.userName || '익명',
            userColor: cursorEvent.userColor || '#3b82f6',
            xPosition: cursorEvent.xPosition,
            yPosition: cursorEvent.yPosition,
          },
        }));
      },
      onTableLock: (event) => {
        console.log('📥 Received TABLE_LOCK:', event);
      },
      onTableUnlock: (event) => {
        console.log('📥 Received TABLE_UNLOCK:', event);
      },
    });

    wsClientRef.current = wsClient;

    // 자동으로 연결 시작
    wsClient.connect();
    setIsWsConnected(true);

    return () => {
      console.log('🔌 Cleaning up WebSocket...');
      wsClient.disconnect();
      setIsWsConnected(false);
    };
  }, [isViewMode, currentUser, updateTablePosition]);

  // WebSocket 테스트 함수들
  const handleWsConnect = useCallback(() => {
    if (wsClientRef.current) {
      wsClientRef.current.connect();
      setIsWsConnected(true);
      console.log('✅ WebSocket connection initiated');
    }
  }, []);

  const handleWsDisconnect = useCallback(() => {
    if (wsClientRef.current) {
      wsClientRef.current.disconnect();
      setIsWsConnected(false);
      console.log('❌ WebSocket disconnected');
    }
  }, []);

  const handleWsSendTest = useCallback(() => {
    if (wsClientRef.current) {
      // 테스트 메시지: 테이블 이동
      wsClientRef.current.sendTableMove(1, 100, 200);
      console.log('📤 Sent test TABLE_MOVE message');
    }
  }, []);


  const handleCloseImportModal = useCallback(() => {
    setActiveTool('cursor');
    setIsImportProcessing(false);
  }, [setActiveTool]);

  const handleImportSubmit = useCallback(
    (ddl: string) => {
      setIsImportProcessing(true);
      window.setTimeout(() => {
        const trimmed = ddl.trim();
        const hasCreateTable = /create\s+table/i.test(trimmed);
        const forceError = /force_error/i.test(trimmed);
        const isValid = trimmed.length > 0 && hasCreateTable && !forceError;

        if (isValid) {
          replaceTables(cloneTables(IMPORT_CORRECTED_TABLES));
          setImportResult(null);
          setIsImportResultOpen(false);
        } else {
          setImportResult({
            type: 'error',
            correctedSql: IMPORT_ERROR_SQL,
            changeSummary: IMPORT_ERROR_CHANGE_SUMMARY,
            tables: cloneTables(IMPORT_CORRECTED_TABLES),
          });
          setIsImportResultOpen(true);
        }

        setIsImportProcessing(false);
        handleCloseImportModal();
      }, 600);
    },
    [handleCloseImportModal, replaceTables],
  );

  const handleImportResultConfirm = useCallback(() => {
    if (importResult?.tables) {
      replaceTables(cloneTables(importResult.tables));
    }
    setImportResult(null);
    setIsImportResultOpen(false);
  }, [importResult, replaceTables]);

  const handleImportResultClose = useCallback(() => {
    setImportResult(null);
    setIsImportResultOpen(false);
    setIsImportRetryOpen(true);
  }, []);

  const handleImportRetryConfirm = useCallback(() => {
    setIsImportRetryOpen(false);
    setActiveTool('import');
    setIsImportProcessing(false);
  }, [setActiveTool]);

  const handleCloseExportModal = useCallback(() => {
    setActiveTool('cursor');
    setSqlPreview('');
    setIsPreviewLoading(false);
    setIsCopying(false);
    setShowCopyToast(false);
  }, [setActiveTool]);

  const handlePreviewClick = useCallback((database: ExportDatabase) => {
    setIsPreviewLoading(true);
    setTimeout(() => {
      setSqlPreview(dummySqlPreview[database]);
      setIsPreviewLoading(false);
    }, 400);
  }, []);

  const handleCopyClick = useCallback(
    async (database: ExportDatabase) => {
      const textToCopy =
        sqlPreview && sqlPreview.trim().length > 0
          ? sqlPreview
          : dummySqlPreview[database];

      if (!textToCopy) {
        return;
      }

      if (!sqlPreview || sqlPreview.trim().length === 0) {
        setSqlPreview(dummySqlPreview[database]);
      }

      setIsCopying(true);
      try {
        if (
          navigator.clipboard &&
          typeof navigator.clipboard.writeText === 'function'
        ) {
          await navigator.clipboard.writeText(textToCopy);
        } else {
          const textarea = document.createElement('textarea');
          textarea.value = textToCopy;
          textarea.style.position = 'fixed';
          textarea.style.opacity = '0';
          document.body.appendChild(textarea);
          textarea.focus();
          textarea.select();
          document.execCommand('copy');
          document.body.removeChild(textarea);
        }
        setShowCopyToast(true);
      } catch (error) {
        console.error('SQL 복사에 실패했습니다.', error);
      } finally {
        setIsCopying(false);
      }
    },
    [sqlPreview],
  );

  useEffect(() => {
    if (!showCopyToast) {
      return;
    }

    const timer = window.setTimeout(() => {
      setShowCopyToast(false);
    }, 2000);

    return () => window.clearTimeout(timer);
  }, [showCopyToast]);

  const isImportModalOpen = activeTool === 'import';
  const isExportModalOpen = activeTool === 'export';

  return (
    <>
      <div className="flex w-full flex-col">
        <div className="flex h-[calc(100vh-70px)] min-h-[calc(100vh-70px)] overflow-hidden bg-my-white">
          {/* 뷰어 모드에서는 왼쪽 사이드바 숨김 */}
          {!isViewMode && <LeftSideBar />}
          <div className="flex min-h-0 flex-1 overflow-hidden">
            <WorkspaceCanvas mode={mode} />
          </div>
          {/* 뷰어 모드에서는 오른쪽 사이드바 숨김 */}
          {!isViewMode && <RightSideBar />}
        </div>
      </div>

      {/* 뷰어 모드에서는 Import/Export 모달 숨김 */}
      {!isViewMode && (
        <>
          <ImportModal
            isOpen={isImportModalOpen}
            onClose={handleCloseImportModal}
            onSubmit={handleImportSubmit}
            isProcessing={isImportProcessing}
          />
          <ExportModal
            isOpen={isExportModalOpen}
            onClose={handleCloseExportModal}
            sqlPreview={sqlPreview}
            onClickPreview={handlePreviewClick}
            onClickDownload={handleCopyClick}
            isPreviewLoading={isPreviewLoading}
            isDownloadLoading={isCopying}
          />
          {importResult && (
            <ImportResultModal
              isOpen={isImportResultOpen}
              onClose={handleImportResultClose}
              onConfirm={handleImportResultConfirm}
              type={importResult.type}
              correctedSql={importResult.correctedSql}
              changeSummary={importResult.changeSummary}
            />
          )}
          <ImportRetryModal
            isOpen={isImportRetryOpen}
            message="SQL문을 다시 입력하시기 바랍니다."
            onConfirm={handleImportRetryConfirm}
          />
        </>
      )}
      {showCopyToast && (
        <div className="fixed bottom-6 left-1/2 z-50">
          <div className="-translate-x-1/2 transform">
            <div className="flex items-center gap-2 rounded-[10px] bg-my-black px-6 py-3 text-my-white shadow-lg animate-fadeIn">
              <BuildSuccessIcon className="h-5 w-5" />
              <span className="font-pretendard text-sm font-medium">
                SQL이 복사되었습니다.
              </span>
            </div>
          </div>
        </div>
      )}

      {/* WebSocket 테스트 패널 (개발 중에만 표시) */}
      {!isViewMode && import.meta.env.DEV && (
        <WebSocketTestPanel
          isConnected={isWsConnected}
          onConnect={handleWsConnect}
          onDisconnect={handleWsDisconnect}
          onSendTestMessage={handleWsSendTest}
        />
      )}

      {/* 원격 커서들 렌더링 */}
      {!isViewMode &&
        Object.values(remoteCursors).map((cursor) => (
          <RemoteCursor
            key={cursor.userEmail}
            userName={cursor.userName}
            userColor={cursor.userColor}
            xPosition={cursor.xPosition}
            yPosition={cursor.yPosition}
          />
        ))}
    </>
  );
};

interface WorkSpacePageProps {
  mode?: WorkspaceMode;
}

const WorkSpacePage: React.FC<WorkSpacePageProps> = ({ mode = 'edit' }) => {
  return (
    <WorkspaceProvider>
      <WorkspaceLayout mode={mode} />
    </WorkspaceProvider>
  );
};

export default WorkSpacePage;
